version: "3"

services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - database

volumes:
  postgres:
  pgadmin:

